### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Berrazou** [AdrianCX/pico_hole#1]
I am getting the following error when trying to run the "cmake .." command

"""
CMake Error at CMakeLists.txt:33 (add_subdirectory):
  add_subdirectory given source "random_leds" which is not an existing
  directory.
"""

**Comment by AdrianCX** [comment]
Apologize for that, will update in 30 min or so once I fix this.

**Comment by AdrianCX** [comment]
Fixed, comment if you run into any other issues

**Comment by Berrazou** [comment]
Thanks @AdrianCX
